name: transportation_flutter_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.1
  cool_alert: ^1.1.0
  fluttertoast: ^8.0.9
  flutter_credit_card: ^3.0.1
  country_picker: ^2.0.12
  simple_star_rating: ^0.0.3
  shared_preferences: ^2.0.13
  image_picker: ^0.8.4+11
  dio: ^4.0.4
  flutter_slidable: ^1.2.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/imgs/

